clean:
	rm -f emulation/registers/*
	rm -f emulation/memdumps/*
	rm -f emulation/gdb.txt
	rm -f kernel_page_tables.txt dumpmemory.gdb 
	rm -f setup_cpregs.bin setup_cpregs.S setup_cpregs.o
	rm -f qemu.pid
